# Generated by Django 3.2.5 on 2021-07-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PsValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('command', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ps_values',
                'ordering': ['pid'],
            },
        ),
    ]
